### ISSUE TITLE
error on const

### ISSUE THREAD

**Issue by JamesOlvertone** [smallbasic/smallbasic.samples#1]
SmallBASIC version 0.12.14 SDL Unix_64 Sun,
example: 3d_torus.bas:
 * RTE-ERROR AT 3d_torus.bas:2 * 
Description:
LET: Cannot change a constant (CONST always has global scope)
Opened: 3d_torus.bas 4698 bytes

Other examples that use CONST have the same problem.

**Comment by chrisws** [comment]
Thanks for your report. I've fixed the error.

Cheers,
Chris
